"""schema initial clients devis lignes

Revision ID: 9d693e46af5b
Revises: 
Create Date: 2026-09-29 03:22:26.323565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d693e46af5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telephone', sa.String(length=30), nullable=True),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('cree_le', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint("statut IN ('brouillon', 'envoye', 'accepte', 'refuse')", name='ck_devis_statut'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('lignes_devis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('devis_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantite', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('prix_unitaire', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sous_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('prix_unitaire >= 0', name='ck_ligne_prix'),
    sa.CheckConstraint('quantite > 0', name='ck_ligne_quantite'),
    sa.ForeignKeyConstraint(['devis_id'], ['devis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lignes_devis')
    op.drop_table('devis')
    op.drop_table('clients')
    # ### end Alembic commands ###
